"""Domain index — generate the thin <wiki_base>/<domain>/index.md (design §5.4).

Navigation-only derived file: one row per documented repo (name / one-line / link)
plus a pointer to the domain `_common/`. Regenerated by scanning
`<wiki_base>/<domain>/*/architecture.md`; it never restates content. `index.md`
(not `.index.md`) is intentionally NOT matched by the derived-file lint.
"""

import os

from . import io_utf8, parser

INDEX_NAME = "index.md"


def _repo_dirs(domain_dir):
    """Subdirs of a domain dir that contain an `architecture.md` (sorted; skips _*/.* )."""
    out = []
    try:
        names = os.listdir(domain_dir)
    except OSError:
        return out
    for name in sorted(names):
        if name.startswith(".") or name.startswith("_"):
            continue
        if os.path.isfile(os.path.join(domain_dir, name, "architecture.md")):
            out.append(name)
    return out


_DIGEST_CAP = 6


def _subsystem_names(doc):
    """First-column names of the 子系统清单 table in a generated 系统总览 scaffold.

    Returns the name list, ``[]`` if the heading exists but carries no table, or
    ``None`` when there is no 子系统清单 heading at all — i.e. a single-module root
    doc, whose 说明 should come from its first prose line instead."""
    head = next((h for h in doc.headings if "子系统清单" in h.text), None)
    if head is None:
        return None
    later = [h.line_start for h in doc.headings if h.line_start >= head.line_end]
    end = min(later) if later else len(doc.text)
    tables = parser.tables_in(doc.text, head.line_end, end)
    if not tables:
        return []
    t = tables[0]
    rows = [(s, e) for (s, e) in parser._line_spans(doc.text)
            if t.start <= s < t.rows_end]
    out = []
    for s, e in rows[2:]:  # skip the header row and the |---| delimiter
        cells = parser.split_row(parser._line_content(doc.text, s, e))
        first = cells[0] if cells else ""
        if first and first != "—":
            out.append(first)
    return out


def _subsystem_digest(names):
    """`N 个子系统：a、b、c…` (first _DIGEST_CAP names; trailing `…` when more remain)."""
    n = len(names)
    if n == 0:
        return ""
    shown = "、".join(names[:_DIGEST_CAP])
    if n > _DIGEST_CAP:
        return "{} 个子系统：{}…".format(n, shown)
    return "{} 个子系统：{}".format(n, shown)


def _first_prose(text, lo, hi):
    """First plain-prose line in [lo, hi): skips headings, blockquotes, table rows and
    fenced-code bodies. Returns '' if there is none."""
    in_fence = False
    for s, e in parser._line_spans(text):
        if s < lo:
            continue
        if s >= hi:
            break
        c = parser._line_content(text, s, e).strip()
        if c.startswith("```") or c.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence or not c or c[0] in "#>|":
            continue
        return c
    return ""


def _summary(doc):
    """(H1 title or None, one-line 说明) of an architecture.md doc.

    Preference order:
    1. an authored intro paragraph in the preamble — i.e. before the first ``##``
       section — as carried by refined multi-subsystem roots like fms-server;
    2. else, for a bare 系统总览 scaffold, a digest of the 子系统清单 (`N 个子系统：…`);
    3. else the first prose line anywhere under the H1, for a single-module root doc
       whose intro lives under ``## 概述``."""
    h1 = next((h for h in doc.headings if h.level == 1), None)
    title = h1.text if h1 else None
    after = h1.line_end if h1 else doc.frontmatter.end
    intro = _first_prose(doc.text, after, doc.preamble_end)
    if intro:
        return title, intro
    names = _subsystem_names(doc)
    if names is not None:
        return title, _subsystem_digest(names)
    return title, _first_prose(doc.text, after, len(doc.text))


def _cell(s):
    return s.replace("|", "\\|")


def _render(domain, rows):
    """rows: list of (repo, title, one_line)."""
    lines = [
        "# {} 域索引".format(domain),
        "",
        "> 本页由引擎自动生成（域内各仓总览 + 域级公共文档导航），仅作导航、不复述内容。",
        "",
        "## 仓",
        "",
        "| 仓 | 说明 | 文档 |",
        "|---|---|---|",
    ]
    for repo, title, one_line in rows:
        link = "[{}](./{}/architecture.md)".format(_cell(title), repo)
        lines.append("| {} | {} | {} |".format(_cell(repo), _cell(one_line) or "—", link))
    lines += [
        "",
        "## 域级公共文档",
        "",
        "见 [`_common/`](./_common/)。",
        "",
    ]
    return "\n".join(lines) + "\n"


def build_index(wiki_base, domain):
    domain_dir = os.path.join(wiki_base, domain)
    rows = []
    for repo in _repo_dirs(domain_dir):
        arch = os.path.join(domain_dir, repo, "architecture.md")
        doc = parser.parse(arch, io_utf8.read_text(arch))
        title, one_line = _summary(doc)
        rows.append((repo, title or repo, one_line))
    return _render(domain, rows)


def write_index(wiki_base, domain):
    content = build_index(wiki_base, domain)
    path = os.path.normpath(os.path.join(wiki_base, domain, INDEX_NAME))
    io_utf8.write_text(path, content)
    return path
