"""Domain index — generate the thin <wiki_base>/<domain>/index.md (design §5.4).

Navigation-only derived file: one row per documented repo (name / one-line / link)
plus a pointer to the domain `_common/`. Regenerated by scanning
`<wiki_base>/<domain>/*/architecture.md`; it never restates content. `index.md`
(not `.index.md`) is intentionally NOT matched by the derived-file lint.
"""

import os

from . import io_utf8, parser

INDEX_NAME = "index.md"


def _repo_dirs(domain_dir):
    """Subdirs of a domain dir that contain an `architecture.md` (sorted; skips _*/.* )."""
    out = []
    try:
        names = os.listdir(domain_dir)
    except OSError:
        return out
    for name in sorted(names):
        if name.startswith(".") or name.startswith("_"):
            continue
        if os.path.isfile(os.path.join(domain_dir, name, "architecture.md")):
            out.append(name)
    return out


def _summary(doc):
    """(H1 title or None, first plain-prose line or "") of an architecture.md doc."""
    h1 = next((h for h in doc.headings if h.level == 1), None)
    title = h1.text if h1 else None
    after = h1.line_end if h1 else doc.frontmatter.end
    one_line = ""
    in_fence = False
    for s, e in parser._line_spans(doc.text):
        if s < after:
            continue
        c = parser._line_content(doc.text, s, e).strip()
        if c.startswith("```") or c.startswith("~~~"):
            in_fence = not in_fence
            continue
        if in_fence or not c or c[0] in "#>|":
            continue
        one_line = c
        break
    return title, one_line


def _cell(s):
    return s.replace("|", "\\|")


def _render(domain, rows):
    """rows: list of (repo, title, one_line)."""
    lines = [
        "# {} 域索引".format(domain),
        "",
        "> 本页由引擎自动生成（域内各仓总览 + 域级公共文档导航），仅作导航、不复述内容。",
        "",
        "## 仓",
        "",
        "| 仓 | 说明 | 文档 |",
        "|---|---|---|",
    ]
    for repo, title, one_line in rows:
        link = "[{}](./{}/architecture.md)".format(_cell(title), repo)
        lines.append("| {} | {} | {} |".format(_cell(repo), _cell(one_line) or "—", link))
    lines += [
        "",
        "## 域级公共文档",
        "",
        "见 [`_common/`](./_common/)。",
        "",
    ]
    return "\n".join(lines) + "\n"


def build_index(wiki_base, domain):
    domain_dir = os.path.join(wiki_base, domain)
    rows = []
    for repo in _repo_dirs(domain_dir):
        arch = os.path.join(domain_dir, repo, "architecture.md")
        doc = parser.parse(arch, io_utf8.read_text(arch))
        title, one_line = _summary(doc)
        rows.append((repo, title or repo, one_line))
    return _render(domain, rows)


def write_index(wiki_base, domain):
    content = build_index(wiki_base, domain)
    path = os.path.normpath(os.path.join(wiki_base, domain, INDEX_NAME))
    io_utf8.write_text(path, content)
    return path
